language: node_js
node_js:
- '0.11'
env:
  global:
    secure: LNvLLNUtHVO8qEzntO1B+IGzwQIC7wk9IhalWbLN8KPAzmfG67ng+Kpo1YExnJX0N0mlCUnqHh6jD763KkSca9tsXlIid/lyh0TEXowwpUIObwkEK7Js2lc5jgA5TM5nMX2eb3YEzNiKWQ1Kxwg2s8Z/eikXpX7cSOQQdghojXo=
before_script:
- npm install --quiet -g gulp
- npm install
script:
- gulp ci
- node_modules/.bin/codeclimate < coverage/lcov.info
